# -*- coding: utf-8 -*-
"""genai_gemini.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PpX-0oXWLQlXS1Sa1MPMbdWJGuhsj_0j
"""

import json
data=json.load(open("/content/states_india.geojson"))
print(data)

json.load(open("/content/states_india.geojson"))

for feature in data['features']:
  state_name=feature['properties']['st_nm']
  print(state_name)

type(data)

type(data)['features']

type(data).keys

data['features'][0].keys()

data['features'][0]['properties']

data['features'][0]['properties']['st_nm']

data['features'][1]['properties']['st_nm']

data['features'][5]['properties']['st_nm']

!pip install openai

import openai

openai.api_key="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"

openai.models.list()

models=openai.models.list()

type(models.data)

models.data[1].id

models.data[0].id

models.data[2].id

models.data[3].id

engine_mode="gpt-3.5-turbo"

openai.Completion.create(engine="gpt-3.5-turbo",prompt="tell me about India in 100 words",max_tokens=1024,n=1,temperature=0.5)

!pip install openai==0.28

!pip install langchain_openai

from langchain_openai import chatOpenAI

llm=chatOpenAI(api_key="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")

llm.invoke("HI tell me about tamil")

!pip install -q-U google-generativeai

import google.generativeai as genai

genai.configure(api_key="AIzaSyD_F0ckDzt6wz7uyn5dksh3TE2WDiE9-tU")

for i in genai.list_models():
  print(i.name)

model=genai.GenerativeModel("gemini-pro")

res=model.generate_content("district in tamilnadu")

print(res.text)

res=model.generate_content("where is the salem in india")

print(res.text)

res=model.generate_content("salem is the district in tamilnadu")

print(res.text)

res=model.generate_content("where mettur located in tamilnadu")

print(res.text)

res=model.generate_content("where the cheif minister located in tamilnadu")

print(res.text)

res=model.generate_content("where the cheif minister located in tamilnadu")

print(res.text)

know=model.generate_content("what is meant by gdp and how to achieve it")

print(know.text)

know=model.generate_content("what is meant by dbms and how to study")

print(know.text)

internet=model.generate_content("what is arpanet")

print(internet.text)

internet=model.generate_content("what is meant by 5g")

print(internet.text)

rupees=model.generate_content("which year money is introduced")

print(rupees.text)

rupees=model.generate_content("which year 50 and 100 rupees new note is introduced in india")

print(rupees.text)

bike=model.generate_content("which year the bikes introduced in all over the world")

print(bike.text)

human=model.generate_content("world first born human name")

print(human.text)

women=model.generate_content("world first born women name")

print(women.text)

baby=model.generate_content("world first born baby father and mother name")

print(baby.text)

computer=model.generate_content("first who invented the computer")

print(computer.text)

import google.generativeai as genai

genai.configure(api_key="AIzaSyD_F0ckDzt6wz7uyn5dksh3TE2WDiE9-tU")

vision_model=genai.GenerativeModel("gemini-1.5-flash")

from PIL import Image
Img=Image.open("/content/One_Piece,_Volume_61_Cover_(Japanese) (1).jpg")

Img

res=vision_model.generate_content(["what the image telling",Img])

print(res.text)

